### ISSUE TITLE
How should I get python output?

### ISSUE THREAD

**Issue by Wolfsin** [NumesSanguis/FACSvatar#30]
Thank you for your work, which has helped me a lot.
As you know, openface has not provided python binding library yet, but I need to use some data identified by it. I see that your work can already output openface data in python. If I want to use these data in Python, what should I do?

**Comment by NumesSanguis** [comment]
We modified OpenFace to include ZeroMQ (pyzmq): https://zeromq.org/
This allows for data to be send over sockets (e.g. TCP). So instead of working with Python bindings or something, we send the data from OpenFace over the network, and have a socket listening in Python.
This documentation page is still a draft, but some more information can be found here: https://facsvatar.readthedocs.io/en/v0.4.0/trackers/openface.html

1. My colleague at that time was good with C#, so the ZeroMQ component has only been added to the Windows version with interface. You can download the .exe here: https://github.com/NumesSanguis/FACSvatar/releases/download/v0.3.4-alpha-release/openface_2.1.0_zeromq.zip
2. You can either use FACSvatar directly or write the code for a subscriber yourself:
    a. Start the `process_bridge` module as [described here](https://facsvatar.readthedocs.io/en/v0.4.0/modules/firstrun.html#start-modules). Then [check this line of code](https://github.com/NumesSanguis/FACSvatar/blob/v0.4.0/modules/output_facstofile/main.py#L91) of `output_facstofile`.
    b. Create a subscriber socket. You can find my simple [zeromq publisher-subscriber project here](https://github.com/NumesSanguis/pyzmq-docker/blob/master/sub/main.py). You have to check in the `openface_2.1.0_zeromq.zip` (step 1) for `config.xml` to know the right IP and port.

**Comment by Wolfsin** [comment]
Thank you for your reply.This information can make me work smoothly in the next step.
