### ISSUE TITLE
Avatar Face isn't moving at all

### ISSUE THREAD

**Issue by SilentSin** [NumesSanguis/FACSvatar#5]
Following on from https://github.com/TadasBaltrusaitis/OpenFace/issues/492.

I pasted the MainWindow.xaml.cs straight in and it worked fine, though I do still get the same crash when trying to load webcams so I'll wait for a response on my other issue over there. https://github.com/TadasBaltrusaitis/OpenFace/issues/506

Using `cd` to change the working directory to the folder containing each of the python files before running them seems to have done the trick. I now get both the n_proxy_m_bus.py and pub_facs.py scrolling through lots of data then eventually stopping, but the head in Unity still doesn't do anything. I get the Debug.Logs in ZeroMQFACSvatar.cs for "Setting up subscriber sock" and "sub socket initiliased", but uncommenting the one for "Received messages:" never gets called.

**Comment by NumesSanguis** [comment]
Dear SilentSin,

I wanted to have the new Unity3D project that works with the latest master branch uploaded by now, but unfortunately the experiments I'm running are taking more time than expected. Currently I did some hackish approach for my experiment, so I have to clean-up the code before uploading. I hope to have updated the Unity3D project in 2 days. Documentation will take somewhat longer.

**Comment by NumesSanguis** [comment]
A new Unity3D project has been uploaded that should work with the updated code. Please try again and let me know whether it works :)

**Comment by SilentSin** [comment]
It works :)

I also fixed the crash in OpenFaceOffline (the depth sensor in the RealSense camera shows up as a separate device that fails to give a proper width and height, so I just made it skip over any device with 0 size) and I can stream in real time from there as well.

A couple of things I noticed:

- For some reason you've got UnityCrashHandler64.exe and UnityPlayer.dll in the unity_FACSAvatar folder.
- There's an object called "Missing Prefab" in each of the scenes.
- The female avatar has a very intense neutral expression because her eyes are so wide.

Thanks a lot for the work you've done and the help you've given me.

**Comment by NumesSanguis** [comment]
I also had trouble with getting the RealSense camera to work. Good to know what the problem is.

- Removed, thanks. I accidentally build in my project folder and forgot to remove all files.
- On my current PC there was nothing missing, but my guess is that this is the 'skybox', which is just an image outside the cafe. It doesn't do anything relating to the functionality of FACSvatar. I'll check more properly when I have time.
- All characters are made with [ManuelBastioniLAB](http://www.manuelbastioni.com/). It's an add-on for Blender to easily create humans. On the [wikia page of the add-on](http://manuelbastionilab.wikia.com/wiki/Unity_3D), you can find instructions on how to import them to Unity3D. I guess I put the base eyelids too high, but you can create your own model to better fit your needs.

You're welcome :)
